# Generated by Django 2.2.12 on 2020-08-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Functions',
            new_name='Function',
        ),
    ]
