# Generated by Django 2.2.12 on 2020-08-23 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
            preserve_default=False,
        ),
    ]
